[build-system]
requires = ["uv_build>=0.7.21,<0.8"]
build-backend = "uv_build"

[project]
authors = [
    { name = "Josh", email = "josh@joshthomas.dev" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Framework :: Django",
  # [[[cog
  # import subprocess
  # import cog
  #
  # from noxfile import DJ_VERSIONS
  #
  # for version in DJ_VERSIONS:
  #     if version == "main":
  #         continue
  #     cog.outl(f'  "Framework :: Django :: {version}",')
  # ]]] -->
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.1",
  "Framework :: Django :: 5.2",
  # [[[end]]]
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  # [[[cog
  # import subprocess
  # import cog
  #
  # from noxfile import PY_VERSIONS
  #
  # for version in PY_VERSIONS:
  #     cog.outl(f'  "Programming Language :: Python :: {version}",')
  # ]]] -->
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  # [[[end]]]
  "Programming Language :: Python :: Implementation :: CPython"
]
dependencies = [
  "django>4.2",
  "fastmcp>=2.11.3",
  "mcp-django",
  "pydantic[email]>=2.11.7",
]
description = "MCP server providing a stateful Django shell for LLM assistants."
name = "mcp-django-shell"
readme = "../../README.md"
version = "0.8.0"
requires-python = ">=3.10"

[project.urls]
Documentation = "https://github.com/joshuadavidthomas/mcp-django#README"
Issues = "https://github.com/joshuadavidthomas/mcp-django/issues"
Source = "https://github.com/joshuadavidthomas/mcp-django"

[tool.bumpver]
commit = true
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
current_version = "0.8.0"
push = false  # set to false for CI
tag = false
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
  'version = "{version}"'
]
