name: release

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  pypi:
    runs-on: ubuntu-latest
    needs: test
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Build all packages
        run: |
          uv build

          for package_dir in packages/*/; do
            if [ -f "$package_dir/pyproject.toml" ]; then
              uv build --package $(basename "$package_dir")
            fi
          done

      - name: Upload release assets to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*

      - name: Publish to PyPI
        run: |
          uv publish
